services:
  manian:
    build:
      context: .
      dockerfile: Dockerfile
    image: manian:latest
    container_name: manian-api
    restart: unless-stopped
    networks:
      - shared-proxy-network
    ports:
      - "7175:7175"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7175;
      - TZ=Asia/Taipei
    volumes:
      # 如果需要寫入 logs
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared-proxy-network:
    external: true